# Generated by Django 3.2.3 on 2021-06-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('descripcion_producto', models.CharField(max_length=150, verbose_name='descripcion del producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio del producto')),
                ('fecha_ingreso', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion Del recordatorio')),
                ('estado_producto', models.CharField(max_length=50, verbose_name='Estado del Producto')),
                ('stock_producto', models.SmallIntegerField(verbose_name='Stock del producto')),
                ('categoria_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria')),
            ],
        ),
    ]
